function crearMapeoBaseTetrimino(){
    tetriminosBase={
        "Z":{
            "mapa":[
                createVector(),
                createVector(1,0),
                createVector(0,1),
                createVector(-1,1)
            ],
            "color":"red"
        },
        "S":{
            "mapa":[
                createVector(),
                createVector(-1,0),
                createVector(0,-1),
                createVector(1,-1)
            ],
            "color":"green"
        },
        "J":{
            "mapa":[
                createVector(),
                createVector(-1,0),
                createVector(-1,-1),
                createVector(1,0),
            ],
            "color":"orange",
        },
        "L":{
            "mapa":[
                createVector(),
                createVector(-1,0),
                createVector(1,-1),
                createVector(1,0)
            ],
            "color":"pink"
        },
        "T":{
            "mapa":[
                createVector(),
                createVector(-1,0),
                createVector(1,0),
                createVector(0,-1)
            ],
            "color":"magenta"
        },
        "O":{
            "mapa":[
                createVector(),
                createVector(0,-1),
                createVector(1,-1),
                createVector(1,0)
            ],
            "color":"yellow"
        },
        "I":{
            "mapa":[
                createVector(),
                createVector(-1,0),
                createVector(1,0),
                createVector(2,0)
            ],
            "color":"cyan"
        }
    }
}
